spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://43.201.102.210:3306/sasatech?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)

  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
#
#  datasource:
#    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
#    url: jdbc:h2:~/test  # H2 접속 정보
#    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

server:
  max-http-header-size: 8000000
  port: 8081
  servlet:
    context-path: /api
  error:
    include-message: always

jwt:
  secret:
    key: r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E



logging:
  level:
    root: info


springdoc:
  version: 1.0
  api-docs:
    path: /
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none

  paths-to-match:
    /**

app:
  firebase-configuration-file: ./serviceAccountKey.json
  firebase-bucket: osiopso.appspot.com

  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080

springboot:
  jwt:
    secret: flature!@#

# test