# Generated by Django 4.1.7 on 2023-03-31 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='id',
            old_name='isbns',
            new_name='isbn_books',
        ),
    ]
