# Generated by Django 4.1.7 on 2023-03-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_isbns_id_isbn_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='id',
            old_name='isbn_books',
            new_name='read_books',
        ),
    ]
